refactor: no hipster anchors

diff --git a/roles/git/vars/main.yml b/roles/git/vars/main.yml
--- a/roles/git/vars/main.yml
+++ b/roles/git/vars/main.yml
@@ -1,14 +1,12 @@
 ---
 # vars file for git
 
-git_alias_acp: &git_alias_acp >-
-  !b=$(git branch --show-current); case "$b" in
-  main|master) echo "On main/master. Aborting."; exit 1;;
-  esac; git add . && git commit && git push
-
 git_gitconfig:
   - name: alias.acp
-    value: *git_alias_acp
+    value: >-
+      !b=$(git branch --show-current); case "$b" in
+      main|master) echo "On main/master. Aborting."; exit 1;;
+      esac; git add . && git commit && git push
   - name: alias.ac
     value: "!git add .; git commit"
   - name: alias.gafp
